name: CI (linux)

on:
  workflow_dispatch:
  schedule:
    - cron: '10 20 * * *'
  pull_request:
    paths:
      - "**.zig"
      - ".github/**"
  push:
    branches:
      - main
    paths:
      - "**.zig"
      - ".github/**"

jobs:
  linux:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        zig: [0.12.0, master]
    steps:
      - uses: actions/checkout@v4

      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ matrix.zig }}

      - name: Start services
        uses: ikalnytskyi/action-setup-postgres@v6
        with:
          username: postgres
          password: postgres
          database: postgres
          port: 5432

      - name: mysql for ubuntu
        uses: mirromutth/mysql-action@v1.1
        with:
          character set server: 'utf8'
          collation server: 'utf8_general_ci'
          mysql version: '8.3'
          mysql database: 'public'
          mysql root password: 'password'
          mysql user: 'developer'

      - name: Install deps
        run: |
          make install-deps

      - name: Run examples
        run: |
          pkg-config --libs --cflags libpq mysqlclient
          zig fmt --check src/
          zig build
          zig build run-all --summary all
